### ISSUE TITLE
Document compatibility with MH-Z14

### ISSUE THREAD

**Issue by kolen** [zenria/mh-z19-rs#1]
According to datasheet, another sensor from Zhengzhou Winsen Electronics Technology, MH-Z14 has the same protocol as MH-Z19. At least I can't find any differences.

I tried this crate with MH-Z14 and it reads gas concentration successfully. [This is my example repo](https://github.com/kolen/mh-z14-rust-serial-embedded-hal-example).

I didn't yet checked if Zhengzhou Winsen Electronics Technology has any other sensors with the same protocol. [This is webpage that lists CO2 sensors manufactured by this company](https://www.winsen-sensor.com/sensors/co2-sensor/).

**Comment by zenria** [comment]
Thank you for your findings, I've added it!
