### ISSUE TITLE
u16->bytes conversion is wrong, as is set_detection_range

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [zenria/mh-z19-rs#3]
This library converts a u16 to bytes [as follows](https://github.com/zenria/mh-z19-rs/blob/a2afacf68bce5d3a1ba4f15156d6bd1d732a22d3/src/lib.rs#L95):
```rust
(value & 0xff00 >> 8) as u8,
(value & 0xff) as u8,
```

However, because of [operator precedence](https://doc.rust-lang.org/reference/expressions.html#expression-precedence), this is actually just `(value & 0xff) as u8` twice. Attempting to set detection range to 2000 (0x07D0) instead creates the number 53456 (0xD0D0).

And [in set_detection_range](https://github.com/zenria/mh-z19-rs/blob/a2afacf68bce5d3a1ba4f15156d6bd1d732a22d3/src/lib.rs#L103) this library tries to set the range by writing bytes 3 and 4, but the actual bytes are 6 and 7.

([Supposedly](https://revspace.nl/MH-Z19B#Protocol_.28operation_mode_0.29) MH-Z19B actually respects bytes 4,5,6,7 as range, in which case trying to set detection range to 0-2000 is actually setting it to 0-3489660928.)

**Comment by zenria** [comment]
Thank you, I've also fixed `calibrate_span_point` in the same way.

I released a 0.3.1 version with those fixes
